build:
  maxIssues: 0

config:
  validation: true

complexity:
  active: true
  LongParameterList:
    active: true
    ignoreAnnotated: [ 'Composable' ]
    ignoreDefaultParameters: true
  LongMethod:
    active: true
    ignoreAnnotated: [ 'Composable' ]

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated: [ 'Composable' ]
  TopLevelPropertyNaming:
    active: false # compose style: PascalCase, kotlin style: SCREAMING_SNAKE_CASE
  MatchingDeclarationName:
    active: false

style:
  active: true
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateMember:
    active: true
    ignoreAnnotated: [ 'preview' ]
  WildcardImport:
    active: false

TwitterCompose:
  CompositionLocalAllowlist:
    active: true
    # You can optionally define a list of CompositionLocals that are allowed here
    # allowedCompositionLocals: LocalSomething,LocalSomethingElse
  CompositionLocalNaming:
    active: true
  ContentEmitterReturningValues:
    active: true
    # You can optionally add your own composables here
    # contentEmitters: MyComposable,MyOtherComposable
  ModifierComposable:
    active: true
  ModifierMissing:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
    # You can optionally add your own composables here
    # contentEmitters: MyComposable,MyOtherComposable
  MutableParams:
    active: true
  ComposableNaming:
    active: true
    # You can optionally disable the checks in this rule for regex matches against the composable name (e.g. molecule presenters)
    # allowedComposableFunctionNames: .*Presenter,.*MoleculePresenter
  ComposableParamOrder:
    active: true
  PreviewNaming:
    active: true
  PreviewPublic:
    active: true
    # You can optionally disable that only previews with @PreviewParameter are flagged
    # previewPublicOnlyIfParams: false
  RememberMissing:
    active: true
  UnstableCollections:
    active: true
  ViewModelForwarding:
    active: true
  ViewModelInjection:
    active: true
